In [11]:
import numpy as np

In [12]:
num = "-65536"

In [13]:
real_num = np.int32(num)
real_num

-65536

In [14]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [19]:
np.array([real_num, real_num], np.int32)

array([-65536, -65536])

In [20]:
np.array([num, num], np.int32)

array([-65536, -65536])

In [21]:
# Напишите функцию get_chess, которая принимает на вход длину стороны квадрата a и возвращает двумерный массив формы (a, a), 
# заполненный 0 и 1 в шахматном порядке.
# В левом верхнем углу всегда должен быть ноль.

In [77]:
def get_chess(a):
    arr_len = a * a
    arr_zer = np.zeros(arr_len)
    arr_zer[1::2] = 1
    return arr_zer.reshape(a, a, order='F')

In [78]:
get_chess(4)

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [105]:
def get_chess(a):
    arr_zer = np.zeros((a, a))
    arr_zer[::2, ::2] = 1
    arr_zer[1::2, 1::2] = 1
    return arr_zer

In [106]:
get_chess(4)

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.

Для этого напишите функцию shuffle_seed(<array>),  которая принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.

In [114]:
import numpy as np

In [134]:
def shuffle_seed(array):
    max_seed_value = np.uint32(2**32 - 1)
    seed_value = np.random.randint(max_seed_value, dtype=np.uint32)
    np.random.seed(seed_value)
    return np.random.permutation(array), seed_value

In [129]:
array = [1, 2, 3, 4, 5]
suf, seed = shuffle_seed(array)

In [133]:
type(suf[0])

numpy.int32

Напишите функцию min_max_dist, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

In [149]:
def min_max_dist(*vectors):
    vec_len = len(vectors)
    
    for first in range(0, vec_len - 1):
        for second in range(first + 1, vec_len):
            if first != second:
                current_dist = np.linalg.norm(vectors[first] - vectors[second])
                if first == 0:
                    min_dist = current_dist
                    max_dist = current_dist
                elif current_dist > max_dist:
                    max_dist = current_dist
                elif current_dist < min_dist:
                    min_dist = current_dist
    
    return min_dist, max_dist

In [150]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
vec3 = np.array([7, 8, 9])
min_max_dist(vec1, vec2, vec3)

(5.196152422706632, 10.392304845413264)