In [1]:
import numpy as np

In [3]:
v1 = np.array([2, 10, -2])
v2 = np.array([3, 2, -2])
v3 = np.array([8, 14, -6])

A = np.array([v1, v2, v3]).T
A

array([[ 2,  3,  8],
       [10,  2, 14],
       [-2, -2, -6]])

In [4]:
np.linalg.matrix_rank(A)

2

In [9]:
x0 = np.zeros(4)
x1 = np.array([14.3, 21.2, 8.34, 15.32])
x2 = np.array([4.3, 3.1, 0.36, 12.42])
x3 = np.array([18.6, 24.3, 8.7, 27.74])

y = np.array([133.18, 178.6, 56.7, 145.9])

X = np.array([x0, x1, x2, x3]).T
X

array([[ 0.  , 14.3 ,  4.3 , 18.6 ],
       [ 0.  , 21.2 ,  3.1 , 24.3 ],
       [ 0.  ,  8.34,  0.36,  8.7 ],
       [ 0.  , 15.32, 12.42, 27.74]])

In [10]:
y

array([133.18, 178.6 ,  56.7 , 145.9 ])

In [11]:
# Формула МНК, результат вектор значений коэффициентов w
w = np.linalg.inv(X.T @ X) @ X.T @ y

LinAlgError: Singular matrix

In [12]:
x1 = np.array([14.3, 21.2, 8.34, 15.32])
x2 = np.array([4.3, 3.1, 0.36, 12.42])
x3 = np.array([18.6, 24.3, 8.7, 27.74])

y = np.array([133.18, 178.6, 56.7, 145.9])

X = np.array([x1, x2, x3]).T
X

array([[14.3 ,  4.3 , 18.6 ],
       [21.2 ,  3.1 , 24.3 ],
       [ 8.34,  0.36,  8.7 ],
       [15.32, 12.42, 27.74]])

In [14]:
np.linalg.matrix_rank(X)

2

Ранг матрицы меньше двины векторов r < n. Система линейно зависима.

In [38]:
from sympy import symbols, solveset, Eq, diff, solve

In [28]:
x, y = symbols('x y')

In [29]:
f = (3 - 8 * x - y)**2
f

(-8*x - y + 3)**2

In [30]:
f_diff_x = f.diff(x)
f_diff_x

128*x + 16*y - 48

In [31]:
f_diff_y = f.diff(y)
f_diff_y

16*x + 2*y - 6

In [35]:
f_diff_x.subs({x: 1, y: 1})

96

In [36]:
f_diff_y.subs({x: 1, y: 1})

12

In [43]:
eq1 = Eq(f_diff_x, 0)
eq2 = Eq(f_diff_y, 0)
 
sol = solve([eq1, eq2], [x, y])

In [44]:
sol

{x: 3/8 - y/8}

In [53]:
f_diff_x.subs({x: 1, y: -8})

-48

In [54]:
f_diff_y.subs({x: 1, y: -8})

-6

In [55]:
from sklearn.linear_model import LinearRegression

In [65]:
X = np.array([1, 3, 5]).reshape(-1, 1)
y = np.array([2.1, 2.9, 4.1])

In [66]:
X

array([[1],
       [3],
       [5]])

In [67]:
lr = LinearRegression()
lr.fit(X, y)

In [73]:
print(f"w0 = {lr.intercept_:.2f}, w1={lr.coef_[0]:.2f}")

w0 = 1.53, w1=0.50


Найдите следующую точку градиентного спуска для функции.

Если текущая точка - (0; 1; 1), alpha=0.2.

In [75]:
alpha = 0.2
x1, x2, x3 = symbols('x1 x2 x3')

f = 2 * x1 * x2 + 3 * x1 * x2 * x3 + 3 * x1 ** 2  + 8 * x3 ** 3 + 19
f

3*x1**2 + 3*x1*x2*x3 + 2*x1*x2 + 8*x3**3 + 19

Определяю градиент как вектор частных производных. 

Т.к. мне нужен антиградиент, то меняю знак для каждого элемента вектора

In [91]:
f_diff_x1 = f.diff(x1)
f_diff_x2 = f.diff(x2)
f_diff_x3 = f.diff(x3)
print(f_diff_x1)
print(f_diff_x2)
print(f_diff_x3)

6*x1 + 3*x2*x3 + 2*x2
3*x1*x3 + 2*x1
3*x1*x2 + 24*x3**2


Считаю значение вектора для точки (0; 1; 1)

In [84]:
g0 = f_diff_x1.subs({x1: 0, x2: 1, x3: 1})
g1 = f_diff_x2.subs({x1: 0, x2: 1, x3: 1})
g2 = f_diff_x3.subs({x1: 0, x2: 1, x3: 1})


Получаю градиент

In [85]:
G = np.array([g0, g1, g2], dtype=float)
G

array([ 5.,  0., 24.])

Вычисляю антиградиент умноженный на темп обучения

In [86]:
g = G * (-1) * alpha
g

array([-1. , -0. , -4.8])

In [92]:
g_ = np.array([0, 1, 1])

In [93]:
g_ + g

array([-1. ,  1. , -3.8])

In [95]:
w1, w2 = symbols('w1 w2')

In [96]:
L = (2 - w1 + 3 * w2)**2
L

(-w1 + 3*w2 + 2)**2

In [97]:
from sympy import hessian

In [98]:
H = hessian(L, (w1, w2))
H

Matrix([
[ 2, -6],
[-6, 18]])

In [101]:
H = np.array([[2, -6], [-6, 18]])
H

array([[ 2, -6],
       [-6, 18]])

In [102]:
np.linalg.det(H)

0.0

In [105]:
z = -9 + 0.04*180 + 0.09*51 + 0.03*39
z

3.96

In [106]:
1/(1 + np.exp(-z))

0.9812934900456455