In [1]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
[print(x) for x in range(10)]

0
1
2
3
4
5
6
7
8
9


[None, None, None, None, None, None, None, None, None, None]

In [3]:
emp_list = list()

In [4]:
emp_list

[]

In [5]:
emp_list.append(1)
emp_list.append("d")

In [6]:
len(emp_list)

2

In [7]:
emp_list

[1, 'd']

In [8]:
emp_list.count(0)

0

In [9]:
emp_list.__sizeof__()

72

In [10]:
emp_tuple = tuple()

In [11]:
emp_tuple.__sizeof__()

24

In [12]:
new_set = set(["Hello", "Hi"])

In [13]:
new_set

{'Hello', 'Hi'}

In [14]:
names = ["Alice", "Bob", "Charlie"]
for i, name in enumerate(range(len(names))):
    print(f"Index: {i}, Name: {names[i]}")
# Output:
# Index: 0, Name: Alice
# Index: 1, Name: Bob
# Index: 2, Name: Charlie

Index: 0, Name: Alice
Index: 1, Name: Bob
Index: 2, Name: Charlie


In [15]:
names = ["Alice", "Bob", "Charlie"]
for i, name in enumerate(names):
    print(f"Index: {i}, Name: {names[i]}")

Index: 0, Name: Alice
Index: 1, Name: Bob
Index: 2, Name: Charlie


In [16]:
round(7.9, 0)

8.0

In [17]:
int("19")

19

In [18]:
my_set = {1, 2, 3, 4, 5}

In [19]:
for i in my_set:
    print(i)

1
2
3
4
5


In [20]:
my_dict = {"a": 1, "b": 2, "c": 3}

for key in my_dict:
    print(my_dict[key])

1
2
3


In [21]:
sum_func = lambda a, b: a + b

sum_func(3, 7)

10

In [22]:
lst = [1, 3, 5, 7]

In [23]:
enum_lst = list(enumerate(lst))

In [24]:
for i, val in enum_lst:
    print(f"{i} : {val}")

0 : 1
1 : 3
2 : 5
3 : 7


In [25]:
(i ** 2 for i in range(11) if i % 2 == 0)

<generator object <genexpr> at 0x000001D7E3140520>

In [26]:
[i ** 2 for i in range(11) if i % 2 == 0]

[0, 4, 16, 36, 64, 100]

In [27]:
str_lst = ['dfd', 'rrbgbt', 'wmnfd']

In [28]:
mp = map(lambda x: len(x), str_lst)

In [14]:
ftr = filter(lambda x: x > 3, mp)

In [17]:
list(ftr)

[6, 5]

In [2]:
import numpy as np
import pandas as pd

In [4]:
arr = np.array([1, 3, 5])
arr

array([1, 3, 5])

In [5]:
arr.dtype

dtype('int32')

In [6]:
arr = np.array([1, 3, 5], dtype=np.int8)

In [7]:
arr

array([1, 3, 5], dtype=int8)

In [15]:
arr[0] = '15'

In [16]:
arr

array([15,  3,  5], dtype=int8)

In [17]:
arr.shape

(3,)

In [18]:
arr.ndim

1

In [19]:
arr.size

3