In [63]:
import numpy as np

In [64]:
# как создать матрицу?

In [65]:
# как двумерный массив Numpy
np.array([[1, 1],
           [2, 3],
           [4, 5]])

array([[1, 1],
       [2, 3],
       [4, 5]])

In [67]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1, 2, 3], 
      [4, 5, 6], 
      [7, 8, 9], 
      [10, 11, 12]]


df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print()
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
# размер матрицы
np.shape(A)

(4, 3)

In [68]:
# вектор-столбец
x = np.array([1, 2, 3])
np.reshape(x, (3, 1))

array([[1],
       [2],
       [3]])

In [69]:
# вектор-строка
np.reshape(x, (1, 3))

array([[1, 2, 3]])

In [70]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row, np.shape(x_row))

[[1 2 3]] (1, 3)


In [71]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print()
print('Первая строка матрицы А:')
print(A[0])
print()
print('Третий столбец матрицы А:')
print(A[:, 2])
print()
print('Элемент а_43:')
print(A[3, 2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Первая строка матрицы А:
[1 2 3]

Третий столбец матрицы А:
[ 3  6  9 12]

Элемент а_43:
12


In [33]:
# создание специальных матриц

In [72]:
# нулевая
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
# единичная
np.eye(3) # квадратная, поэтому указывается одна размерность

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# матрица единиц
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
# Диагональная
diagonal = [1, 2, 3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [38]:
# Шаровая
5 * np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [73]:
A = np.array([[1, 1], [2, 3], [4, 5]])
B = np.array([[1, -1], [-2, 3], [4, -5]])

In [74]:
A

array([[1, 1],
       [2, 3],
       [4, 5]])

In [75]:
B

array([[ 1, -1],
       [-2,  3],
       [ 4, -5]])

In [77]:
A + B

array([[2, 0],
       [0, 6],
       [8, 0]])

In [78]:
B + A

array([[2, 0],
       [0, 6],
       [8, 0]])

In [79]:
A - B

array([[ 0,  2],
       [ 4,  0],
       [ 0, 10]])

In [80]:
2 * A

array([[ 2,  2],
       [ 4,  6],
       [ 8, 10]])

In [81]:
A.T

array([[1, 2, 4],
       [1, 3, 5]])

In [47]:
# как транспонировать вектор?
x = np.array([1, 2, 3])
x.T

array([1, 2, 3])

In [82]:
x_col = np.reshape(x, (3, 1))
print(x_col)
print(np.shape(x_col))

[[1]
 [2]
 [3]]
(3, 1)


In [83]:
x_col.T

array([[1, 2, 3]])

In [84]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

(3,)
(3, 1)
(1, 3)


In [85]:
x = np.array([1, 2, 3])
type(x)

numpy.ndarray

Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы numpy:

In [87]:
Husband_Income = np.array([100, 220, 140])
Wife_Income = np.array([150, 200, 130])
Mother_In_Law_Income = np.array([90, 80, 100])

Husband_Consumption = np.array([50, 50, 60])
Wife_Consumption = np.array([100, 80, 140])
Mother_In_Law_Consumption = np.array([100, 20, 140])

Задание 5.1

Составьте матрицу  доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

In [89]:
Inc = np.array([Husband_Income,
          Wife_Income,
          Mother_In_Law_Income]).T
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

Задание 5.2

Составьте матрицу  расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

In [91]:
Cons = np.array([Husband_Consumption,
                 Wife_Consumption,
                 Mother_In_Law_Consumption]).T
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

Задание 5.3

Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

In [94]:
Inc_after_tax = Inc * (1 - 0.13)
Inc_after_tax

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

Задание 5.4

Вычислите матрицу , которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

In [95]:
Balance = Inc_after_tax - Cons
Balance

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])