In [1]:
import numpy as np

# Произведение матриц

In [2]:
# Случайные матрицы
A = np.random.randint(5, 12, (3, 3))
B = np.random.randint(-2, 4, (3, 3))

In [3]:
A

array([[11,  6,  7],
       [11,  9, 11],
       [ 5,  7, 11]])

In [4]:
B

array([[ 3,  0,  3],
       [ 1, -2,  0],
       [ 1,  3,  2]])

In [5]:
# Поэлементное умножение
# Это неправильно! Правильно скалярно умножать строку на столбец
A * B

array([[ 33,   0,  21],
       [ 11, -18,   0],
       [  5,  21,  22]])

In [117]:
# тип np.matrix
# Так производится правильное, скалярное произведение матриц
A_m = np.matrix(A)
B_m = np.matrix(B)
print(A_m * B_m)

[[  6  18 -10]
 [ 12  16 -14]
 [ -3  19   1]]


In [7]:
# Так проще всего. Не используя np.matrix
# Матричное умножение
np.dot(A, B)

array([[46,  9, 47],
       [53, 15, 55],
       [33, 19, 37]])

In [8]:
# Матричное умножение
A @ B

array([[46,  9, 47],
       [53, 15, 55],
       [33, 19, 37]])

In [9]:
# Порядок умножения AB != BA
B @ A

array([[ 48,  39,  54],
       [-11, -12, -15],
       [ 54,  47,  62]])

In [10]:
# Умножение прямоугольных матриц возможно не в любом порядке
A = np.random.randint(5, 12, (3, 5))
B = np.random.randint(-2, 4, (5, 2))
print('A:\n', A)
print('B:\n', B)

A:
 [[10  9  9  5  9]
 [11 10 10  9  6]
 [ 8  6  7  5  5]]
B:
 [[ 3  0]
 [ 1  1]
 [ 3  0]
 [ 1 -2]
 [ 2 -2]]


In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A @ B

array([[ 89, -19],
       [ 94, -20],
       [ 66, -14]])

In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
B @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [13]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A @ B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [14]:
# умножение на специальные матрицы
A = np.random.randint(-4, 4, (4, 4))
D = np.diag([1, 2, 0, -1])

print('A:\n', A)
print('D:\n', D)
print('AD:\n', A @ D)
print('DA:\n', D @ A)

A:
 [[-3 -4 -3 -4]
 [ 3 -4  1  0]
 [ 2  2 -4 -4]
 [-4  2 -4 -2]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-3 -8  0  4]
 [ 3 -8  0  0]
 [ 2  4  0  4]
 [-4  4  0  2]]
DA:
 [[-3 -4 -3 -4]
 [ 6 -8  2  0]
 [ 0  0  0  0]
 [ 4 -2  4  2]]


In [16]:
# умножение на одномерный массив numpy
A = np.array([[1, 0, 1],
              [1, 1, 1]])

b = np.array([-3, 4, 5])

In [17]:
A @ b

array([2, 6])

In [19]:
b @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [20]:
# матрица Грама ортогональной системы векторов
x = np.array([1, 1, 1])
y = np.array([1, 0, -1])
z = np.array([-1, 2, -1])
A = np.array([x, y, z])
print(A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [21]:
# матрица Грама ортогональной системы векторов
A @ A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [22]:
# матрица Грама ортонормированной системы векторов
x_norm = x / np.linalg.norm(x)
y_norm = y / np.linalg.norm(y)
z_norm = z / np.linalg.norm(z)
A_norm = np.array([x_norm, y_norm, z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [23]:
# матрица Грама ортонормированной системы векторов
A_norm @ A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [24]:
# ортонормированные системы рулят! :)
np.round(A_norm @ A_norm.T, 1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

Задание 7.1

Даны матрица A и вектор x.

Найдите произведение матрицы  и вектора в том порядке, в котором их можно умножить.

In [25]:
A = np.array([[5, -1, 3, 1, 2],
              [-2, 8, 5, -1, 1]])

x = np.array([1, 2, 3, 4, 5])

In [26]:
# x трансформируется в вектор-столбец автоматически
A @ x

array([26, 30])

Задание 7.2

Даны две матрицы.
Найдите произведение матриц в том порядке, в котором их можно умножить.

In [27]:
A = np.array([[1, 9, 8, 5],
              [3, 6, 3, 2],
              [3, 3, 3, 3],
              [0, 2, 5, 9],
              [4, 4, 1, 2]])

B = np.array([[1, -1, 0, 1, 1],
              [-2, 0, 2, -1, 1]])

In [28]:
B.shape

(2, 5)

In [29]:
A.shape

(5, 4)

In [30]:
B @ A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

Задание 7.3

Дана система векторов.
Составьте матрицу A, расположив векторы x, y, z в строках.
Найдите матрицу Грама G (матрицу скалярных произведений столбцов матрицы A) системы векторов x, y, z.

In [31]:
x = np.array([1, 2, 1, 0, 4])
y = np.array([2, 1, -1, 1, 0])
z = np.array([-1, 1, -1, 0, 0])

In [32]:
A = np.array([x, y, z])
A

array([[ 1,  2,  1,  0,  4],
       [ 2,  1, -1,  1,  0],
       [-1,  1, -1,  0,  0]])

In [33]:
# Т.к. в условие произведение столбцов, то сначала транспонирую матрица
G = A.T @ A

In [34]:
G

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

УСЛОВИЕ ДЛЯ ЗАДАНИЙ 7.4 И 7.5

В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей

In [35]:
import pandas as pd

In [36]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [37]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [38]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

Задание 7.4

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят салону определённую комиссию.

Вектор комиссий

In [39]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [40]:
total_income = Price_DF * Count_DF
total_income

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня               20.0              7.5         12.0     12.0  10.0
Борис              3.6             52.5          3.0     25.0   6.0
Вика              24.0             24.0          0.0     15.0   8.0
Галя               7.2              9.6         50.4     11.2  10.0
Дима              15.0             87.5         54.0     25.0  27.0
Егор              50.0             15.0          6.0     34.0  30.0
Женя              24.2              1.0          6.0     12.5  34.0
Юра               31.5              0.0         77.5     31.0  56.0

In [41]:
salon_profit = Price_DF * Count_DF * com
salon_profit

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня               4.00             1.50         3.60     1.20   1.0
Борис             0.72            10.50         0.90     2.50   0.6
Вика              4.80             4.80         0.00     1.50   0.8
Галя              1.44             1.92        15.12     1.12   1.0
Дима              3.00            17.50        16.20     2.50   2.7
Егор             10.00             3.00         1.80     3.40   3.0
Женя              4.84             0.20         1.80     1.25   3.4
Юра               6.30             0.00        23.25     3.10   5.6

In [42]:
salon_profit.sum(axis=1).values

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

Задание 7.5

Найдите вектор прибыли стилистов

In [43]:
(total_income - salon_profit).sum(axis=1).values

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

Найти определители матрицы

In [44]:
BB = np.array([[2, 0, 0],
              [0, 1, 0],
              [0, 0, 4]])
BB

array([[2, 0, 0],
       [0, 1, 0],
       [0, 0, 4]])

Определитель диагональной матрицы - произведение по главной диагонали

In [48]:
2*1*4

8

In [45]:
np.linalg.det(BB)

7.999999999999998

Обратная матрица

In [46]:
BB_1 = np.linalg.inv(BB)
BB_1

array([[0.5 , 0.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.25]])

In [47]:
np.linalg.det(BB_1)

0.12500000000000003

Определитель обратной матрицы равен 1/определитель основной матрицы

In [49]:
1/8

0.125