In [2]:
import numpy as np

In [3]:
# обратная матрица - все ок
A1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 10]])

print('A1:\n',A1)

A1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [4]:
print('rk(A1):\n', np.linalg.matrix_rank(A1))

rk(A1):
 3


In [5]:
# обратная матрица - все ок
A1_inv = np.linalg.inv(A1)
print('A1 inversed:\n', A1_inv)

A1 inversed:
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [6]:
# обратная матрица - все ок
print('A1 @ A1 inversed=E check:\n', A1 @ A1_inv, 1)
print()
print(np.round(A1 @ A1_inv, 1))
print('check OK')

A1 @ A1 inversed=E check:
 [[1.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [8.88178420e-16 0.00000000e+00 1.00000000e+00]] 1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
check OK


In [7]:
# обратная матрица - вырожденный случай
A2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [1, 2, 3]])

print('A2:\n', A2)

A2:
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


In [8]:
# обратная матрица - вырожденный случай
print('rk(A2):\n', np.linalg.matrix_rank(A2))

rk(A2):
 2


In [9]:
# обратная матрица - вырожденный случай
# np.linalg.inv(A2)

In [10]:
# обратная матрица - magic
A3 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

print('A3:\n', A3)

A3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# обратная матрица - magic
print('rk(A3):\n', np.linalg.matrix_rank(A3))

rk(A3):
 2


In [12]:
# обратная матрица - magic
# print('A3 inversed:\n', np.linalg.inv(A3))

In [13]:
# # обратная матрица - magic
# print('A3 @ A3 inversed = E check:\n', A3 @ np.linalg.inv(A3))
# print('check failed')

In [14]:
print('det(A1)):\n', np.linalg.det(A1))

det(A1)):
 -2.9999999999999996


In [15]:
print('det(A2)):\n', np.linalg.det(A2))

det(A2)):
 0.0


In [16]:
print('det(A3)):\n', np.linalg.det(A3))

det(A3)):
 0.0


In [17]:
# обратная матрица - неустойчивость
A4 = np.array([[1, 2, 3],
               [4, 5, 6],
               [1, 2, 3.00005]])

print('A4:\n', A4)
print('rk(A4):\n', np.linalg.matrix_rank(A4))
print('det(A4):\n', np.linalg.det(A4))
print('A4 inverse:\n', np.linalg.inv(A4))

A4:
 [[1.      2.      3.     ]
 [4.      5.      6.     ]
 [1.      2.      3.00005]]
rk(A4):
 3
det(A4):
 -0.00014999999999965044
A4 inverse:
 [[-2.00016667e+04  6.66666667e-01  2.00000000e+04]
 [ 4.00013333e+04 -3.33333333e-01 -4.00000000e+04]
 [-2.00000000e+04  0.00000000e+00  2.00000000e+04]]


In [18]:
# обратная матрица - неустойчивость вблизи нулевого определителя
A5 = np.array([[1, 2, 3],
               [4, 5, 6],
               [1, 2, 3.00000005]])

print('A5:\n', A5)
print('rk(A5):\n', np.linalg.matrix_rank(A5))
print('det(A5):\n', np.linalg.det(A5))
print('A5 inverse:\n', np.linalg.inv(A5))

A5:
 [[1.         2.         3.        ]
 [4.         5.         6.        ]
 [1.         2.         3.00000005]]
rk(A5):
 3
det(A5):
 -1.5000000042064706e-07
A5 inverse:
 [[-2.00000016e+07  6.66666667e-01  1.99999999e+07]
 [ 4.00000012e+07 -3.33333333e-01 -3.99999999e+07]
 [-1.99999999e+07  0.00000000e+00  1.99999999e+07]]


In [19]:
# обратимость матрицы Грама линейно независимой системы векторов
v1 = np.array([1, 2, 1])
v2 = np.array([1, 1, 1])
A = np.array([v1, v2]).T
G = A.T @ A
print('A:\n', A)
print('Матрица Грама:\n', G)

A:
 [[1 1]
 [2 1]
 [1 1]]
Матрица Грама:
 [[6 4]
 [4 3]]


In [20]:
print('Ранг матрицы Грама:\n', np.linalg.matrix_rank(G))

Ранг матрицы Грама:
 2


In [21]:
print('Определитель матрицы Грама:\n', np.linalg.det(G))

Определитель матрицы Грама:
 2.0000000000000004


In [22]:
print('Обратная к матрице Грама:\n', np.linalg.inv(G))

Обратная к матрице Грама:
 [[ 1.5 -2. ]
 [-2.   3. ]]


Задание 10.1

Дана матрица A.
Найдите матрицу, обратную матрице A.

In [23]:
A = np.array([[8, 6, 11],
              [7, 5, 9],
              [6, 10, 6]])
A

array([[ 8,  6, 11],
       [ 7,  5,  9],
       [ 6, 10,  6]])

In [24]:
A_inv = np.linalg.inv(A)
A_inv

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

В качестве ответа запишите элемент из первого столбца второй строки, округлив его до трёх знаков после точки-разделителя.

In [25]:
np.round(A_inv[1, 0], 3)

0.375

УСЛОВИЕ ДЛЯ ЗАДАНИЙ 10.2-10.7

In [26]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

Задание 10.2

Найдите ранг системы векторов v1, v2, v3, v4.

Для этого создайте матрицу системы векторов.

Векторы в матрице расположите в столбцы.

In [27]:
A = np.array([v1, v2, v3, v4]).T
A

array([[ 9,  2,  4,  3],
       [10,  0,  0, -4],
       [ 7,  5,  0,  3],
       [ 7,  1,  4, -1],
       [ 9,  4,  1, -4]])

In [28]:
np.linalg.matrix_rank(A)

4

Ранг матрицы A, составленной из векторов v1, v2, v3, v4, равен 4, что равно количеству векторов в системе.

Это значит, что система векторов является линейно независимой.

Задание 10.4

Найдите матрицу Грама системы векторов v1, v2, v3, v4: G. В качестве ответа запишите элемент из четвёртого столбца первой строки.

In [29]:
G = A.T @ A
G

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

In [30]:
G[0, 3]

-35

Задание 10.5

Найдите определитель матрицы Грама. Ответ округлите до целого числа.

In [31]:
np.round(np.linalg.det(G), 0)

3716648.0

Задание 10.6

Является ли матрица Грама вырожденной?

Нет, т.к. определитель матрицы отличен от нуля, значит матрица не вырождена.

In [32]:
np.linalg.matrix_rank(G)

4

Задание 10.7

Найдите обратную матрицу к матрице Грама.

В качестве ответа запишите элемент из первого столбца третьей строки, округлив его до трёх знаков после точки-разделителя.

In [33]:
G_inv = np.linalg.inv(G)
G_inv

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [34]:
np.round(G_inv[2, 0], 3)

-0.026

In [35]:
np.linalg.matrix_rank(np.array([[2, 3, 8],
          [10, 2, 14],
          [-2, -2, -6]]))

2

Задание 4.8

Составьте корреляционную матрицу для системы векторов

In [36]:
x1 = np.array([5.1, 1.8, 2.1, 10.3, 12.1, 12.6])
x2 = np.array([10.2, 3.7, 4.1, 20.5, 24.2, 24.1])
x3 = np.array([2.5, 0.9, 1.1, 5.1, 6.1, 6.3])

In [37]:
X = np.array([x1, x2, x3]).T
X

array([[ 5.1, 10.2,  2.5],
       [ 1.8,  3.7,  0.9],
       [ 2.1,  4.1,  1.1],
       [10.3, 20.5,  5.1],
       [12.1, 24.2,  6.1],
       [12.6, 24.1,  6.3]])

In [38]:
import pandas as pd

In [39]:
corr_df = pd.DataFrame(X).corr()
corr_df

0         1         2
0  1.000000  0.999255  0.999837
1  0.999255  1.000000  0.999066
2  0.999837  0.999066  1.000000

Чему равен ранг полученной корреляционной матрицы?

In [40]:
np.linalg.matrix_rank(corr_df.values)

3

Чему равен определитель полученной корреляционной матрицы? 

Ответ округлите до седьмого знака после точки-разделителя.

In [41]:
np.round(np.linalg.det(corr_df.values), 7)

5e-07

In [46]:
x = np.array([1, 3, -2, 9])
y = np.array([3, 7, -5, 21])

In [47]:
X = np.array([np.ones(4),
          x,
          x * x]).T
X

array([[ 1.,  1.,  1.],
       [ 1.,  3.,  9.],
       [ 1., -2.,  4.],
       [ 1.,  9., 81.]])

In [50]:
w = np.linalg.inv(X.T @ X) @ X.T @ y
w.round(1)

array([ 0.1,  2.5, -0. ])