In [1]:
import numpy as np

In [5]:
x = np.array([1, 3, -2, 9])
y = np.array([3, 7, -5, 21])

In [6]:
X = np.array([np.ones(4), x, x * x]).T
X

array([[ 1.,  1.,  1.],
       [ 1.,  3.,  9.],
       [ 1., -2.,  4.],
       [ 1.,  9., 81.]])

In [7]:
w = np.linalg.inv(X.T @ X) @ X.T @ y
w.round(1)

array([ 0.1,  2.5, -0. ])

Задание 7.4

Вычислите коэффициенты линейной регрессии с L2-регуляризацией, используя аналитическую формулу Тихонова

In [18]:
# вектора признаков
x1 = np.array([5, 9, 4, 3, 5])
x2 = np.array([15, 18, 18, 19, 19])
x3 = np.array([7, 6, 7, 7, 7])

# вектор правильных ответов
y = np.array([24, 22, 35, 33, 36])

# коэффициент регуляризации
alpha = 1

In [23]:
# вектора призднаков собираю в матрицу добавив единичный вектор для свободного члена w0
X = np.array([np.ones(5), x1, x2, x3]).T
X

array([[ 1.,  5., 15.,  7.],
       [ 1.,  9., 18.,  6.],
       [ 1.,  4., 18.,  7.],
       [ 1.,  3., 19.,  7.],
       [ 1.,  5., 19.,  7.]])

In [25]:
X.shape

(5, 4)

In [26]:
# Создаю единичную матрицу в размер равный количеству параметров
E = np.eye(X.shape[1])
E

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
# Получаю оценку коэффициентов регрессии по МНК с регуляризацией Тихонова
w = np.linalg.inv(X.T @ X + alpha * E) @ X.T @ y
w.round(2)

array([-0.09, -1.71,  1.91,  0.73])