In [1]:
import numpy as np

In [2]:
num = "-65536"

In [3]:
real_num = np.int32(num)
real_num

-65536

In [4]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [5]:
np.array([real_num, real_num], np.int32)

array([-65536, -65536])

In [6]:
np.array([num, num], np.int32)

array([-65536, -65536])

In [7]:
# Напишите функцию get_chess, которая принимает на вход длину стороны квадрата a и возвращает двумерный массив формы (a, a), 
# заполненный 0 и 1 в шахматном порядке.
# В левом верхнем углу всегда должен быть ноль.

In [8]:
def get_chess(a):
    arr_len = a * a
    arr_zer = np.zeros(arr_len)
    arr_zer[1::2] = 1
    return arr_zer.reshape(a, a, order='F')

In [9]:
get_chess(4)

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [10]:
def get_chess(a):
    arr_zer = np.zeros((a, a))
    arr_zer[::2, ::2] = 1
    arr_zer[1::2, 1::2] = 1
    return arr_zer

In [11]:
get_chess(4)

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.

Для этого напишите функцию shuffle_seed(<array>),  которая принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.

In [12]:
import numpy as np

In [13]:
def shuffle_seed(array):
    max_seed_value = np.uint32(2**32 - 1)
    seed_value = np.random.randint(max_seed_value, dtype=np.uint32)
    np.random.seed(seed_value)
    return np.random.permutation(array), seed_value

In [14]:
array = [1, 2, 3, 4, 5]
suf, seed = shuffle_seed(array)

In [15]:
type(suf[0])

numpy.int32

Напишите функцию min_max_dist, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

In [16]:
def min_max_dist(*vectors):
    vec_len = len(vectors)
    
    for first in range(0, vec_len - 1):
        for second in range(first + 1, vec_len):
            if first != second:
                current_dist = np.linalg.norm(vectors[first] - vectors[second])
                if first == 0:
                    min_dist = current_dist
                    max_dist = current_dist
                elif current_dist > max_dist:
                    max_dist = current_dist
                elif current_dist < min_dist:
                    min_dist = current_dist
    
    return min_dist, max_dist

In [17]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
vec3 = np.array([7, 8, 9])
min_max_dist(vec1, vec2, vec3)

(5.196152422706632, 10.392304845413264)

Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

In [18]:
def any_normal(*vectors):
    vec_len = len(vectors)
    
    for first in range(0, vec_len - 1):
        for second in range(first + 1, vec_len):
            if first != second:
                if np.dot(vectors[first], vectors[second]) == 0:
                    return True
                
    
    return False

In [19]:
vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))

True


Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). 
Это поля для игры в лото.

Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).

Функция возвращает полученный массив.

In [20]:
def get_loto(num):
    return np.random.randint(1, 101, size=(num, 5, 5))

In [21]:
get_loto(3)

array([[[50, 38, 21, 33, 80],
        [20, 56, 58, 39, 48],
        [66, 72, 39, 94, 24],
        [57, 82, 96,  8, 45],
        [83, 73, 95, 77, 54]],

       [[53, 82, 37, 39, 86],
        [23, 81, 65, 59,  2],
        [50, 52, 67, 62, 93],
        [94, 53, 82, 41, 10],
        [ 4, 39, 98, 60, 26]],

       [[10, 84, 10, 53, 90],
        [31, 92, 39, 82, 54],
        [92, 91, 61, 31, 85],
        [44, 41, 92,  9, 19],
        [80,  9,  2, 65, 85]]])

Напишите функцию get_unique_loto(num). Она так же, как и функция в задании 10.10, 
генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.

Функция также должна возвращать массив формы num x 5 x 5.

In [22]:
def get_unique_loto(num):
    all_numbers = np.arange(1, 101)
    arr = np.zeros(num)
    
    for i in range(num):
        arr[i] = np.random.choice(all_numbers, size=(5, 5), replace=False)
        
    return arr

In [23]:
get_unique_loto(1)