In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('data\Advertising.zip', index_col=0)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 1 to 200
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 7.8 KB


In [4]:
df

TV  radio  newspaper  sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

Использую только один признак TV

In [5]:
X = df['TV']
y = df['sales']
n = len(y)

# Добавляю столбец единиц для коэффициента w0
X = np.append(np.ones((n, 1)), X.values.reshape(n, 1), axis=1)
y = df['sales'].values.reshape(n, 1)

# вектор коэффициентов инициирую нулями
par = np.zeros((2, 1))

In [6]:
# функция ошибки
def cost_function(X, y, par):
    y_pred = X @ par
    # квадрат ошибки
    error = (y_pred - y)**2
    return np.mean(error)

In [7]:
def grad_d(X, y, par, alpha, iterations):
    costs = []
    for i in range(iterations):
        y_pred = X @ par
        der = np.dot(X.transpose(), (y_pred - y)) / len(y_pred)
        par -= alpha * der
        costs.append(cost_function(X, y, par))
    return par, costs

In [8]:
par, costs = grad_d(X, y, par, 0.000025, 1000000)

In [9]:
par

array([[7.02008764],
       [0.04760015]])

In [10]:
import numpy as np
import statsmodels.api as sm
mod = sm.OLS(y, X)
res = mod.fit()
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                     312.1
Date:                Wed, 28 Jun 2023   Prob (F-statistic):           1.47e-42
Time:                        11:33:34   Log-Likelihood:                -519.05
No. Observations:                 200   AIC:                             1042.
Df Residuals:                     198   BIC:                             1049.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.0326      0.458     15.360      0.0

In [11]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X, y)
print(model.coef_)
print(model.intercept_)

[[0.         0.04753664]]
[7.03259355]


Задание 8.3

Попробуем применить градиентный спуск для решения реальной задачи линейной регрессии. 

Наша цель будет состоять в том, чтобы построить простую модель линейной регрессии для прогнозирования продаж некоторого продукта на основе количества денег, потраченных на рекламу.

Постройте модель, аналогичную той, что была разобрана в видео выше, но с тремя предикторами.

Все веса изначально возьмите равными 0, скорость обучения задайте как 0.00005 и обучите модель на 500000 итераций.

В качестве ответов введите полученные веса для трех предикторов. Ответы округлите до третьего знака после точки-разделителя.

In [12]:
TARGET = 'sales'

X, y = df.drop(columns=TARGET), df[TARGET]
n = len(y)

# количество признаков
param_n = X.shape[1]

# Добавляю столбец единиц для коэффициента w0
X = np.append(np.ones((n, 1)), X.values.reshape(n, param_n), axis=1)
y = y.values.reshape(n, 1)

# количество признаков после добавления векторая едениц для w0
param_n = X.shape[1]
# вектор коэффициентов инициирую нулями
par = np.zeros((param_n, 1))

In [13]:
par, costs = grad_d(X, y, par, 0.00005, 500000)

In [19]:
par

array([[ 2.86254595e+00],
       [ 4.59731305e-02],
       [ 1.89405798e-01],
       [-5.73781627e-04]])

In [17]:
pd.Series(par.reshape(-1,)).round(3)

0    2.863
1    0.046
2    0.189
3   -0.001
dtype: float64