In [1]:
import schedule # Импортируем модуль schedule

In [3]:
# Рассмотрим вариант автоматического запуска простой функции
def task(): 
    print('Hello! I am a task!') 
    return

In [4]:
task()

Hello! I am a task!


In [5]:
schedule.every(15).minutes.do(task)

Every 15 minutes do task() (last run: [never], next run: 2022-04-11 12:42:14)

In [1]:
a = [1,2,3]
b = a
c = [1,2,3]
print(a == b, a == c, a is b, a is c)

True True True False


In [2]:
two = ("a", "b", "c", "d")

In [3]:
type(two)

tuple

In [11]:
one = [1, "2", 3, "4"]
two = ("a", "b", "c", "d")

In [5]:
one.append(5)

In [6]:
two.append("f")

AttributeError: 'tuple' object has no attribute 'append'

In [7]:
one.extend(two)

In [8]:
two.extend(one)

AttributeError: 'tuple' object has no attribute 'extend'

In [12]:
three = two + ("f", 'g')

In [14]:
three

('a', 'b', 'c', 'd', 'f', 'g')

In [10]:
three = one + two

TypeError: can only concatenate list (not "tuple") to list

In [15]:
config = {
    "server": {
        "host": "127.0.0.1",
        "port": "22"
    },
    "configuration": {
        "ssh": {
            "access": True,
            "login": "some",
            "password": "some"
        },
        "name": "2491Oaaf1414"
    }
}

In [16]:
config['configuration']['ssh']['login']

'some'

In [17]:
fddf = 'jk jhuy 9 f65 ggj'

In [19]:
'!'.join(fddf.split(' '))

'jk!jhuy!9!f65!ggj'

In [24]:
s = '541 234'

In [26]:
s.isnumeric()

False

In [30]:
list(range(10, 181, 5))

[10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180]

In [31]:
def new_func():
    pass

In [33]:
print(new_func())

None


In [36]:
import numpy as np

In [39]:
values = np.array([1, 2, 3, 4 , 5])

In [40]:
values

array([1, 2, 3, 4, 5])

In [43]:
values = values - values.min()

In [44]:
values

array([0, 1, 2, 3, 4])

In [47]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [64]:
products={
    "Oranges (packaged)": 114.99, 
    "Candy (Rotfront)": 280.00,
    "Boiled sausage": 199.99,
    "Juice J7 (orange)": 119.99,
    "Trout (Seven Seas)": 399.99
}

stocks = {
    "Boiled sausage": "33%",
    "Juice J7 (orange)": "12%",
    "Trout (Seven Seas)": "18%"
}

In [85]:
def apply_discounts(products, stocks):
    """
    Напишите функцию apply_discounts(), которая снижает цену продуктов в словаре products на указанный в словаре stocks процент. 
    Функция должна вернуть результирующий словарь, ключи которого — товары, а значения — новые цены.
    Если продукта из словаря stocks нет в словаре products, то его необходимо пропустить. Цены округлите до второго знака после запятой.
    """
    new_products = dict()
    
    for prod_name, price in products.items():
        discount = stocks.get(prod_name)
        
        if discount is not None:
            discount = float(discount.replace('%', '')) * 0.01
            
            price = round(price * (1 - discount), 2)
        
        new_products[prod_name] = price
    
    return new_products
        
        
    
    

In [86]:
new_products = apply_discounts(products, stocks)
print(new_products)

{'Oranges (packaged)': 114.99, 'Candy (Rotfront)': 280.0, 'Boiled sausage': 133.99, 'Juice J7 (orange)': 105.59, 'Trout (Seven Seas)': 327.99}
